name: linuxcrate
description: A powerful utility app for linux.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_feather_icons: ^1.0.3
  glob: ^2.0.1
  google_fonts: ^1.0.0
  json_annotation: 3.1.1
  json_serializable: 3.5.1
  path: ^1.8.0
  shared_preferences: ^2.0.5
  string_similarity: ^2.0.0
  system_info: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null

flutter:
  uses-material-design: true
